### ISSUE TITLE
Style enhancements

### ISSUE THREAD

**Issue by astral-sa** [astral-sa/salr#63]
- [x] #104 - Apply 'tan' bookmark coloring to tan bookmarks in forums
- How we color the unread bookmarks isn't customizable. Should it be? That would remove the need for any extra preference specifically for the above.

Good time to work on #59 - Simplify Styles as well.
- [x] #106 - Move poster note styles into a class
- [x] #107 - Move mod/admin styles into classes in thread list
- [x] #111 - Move mod/admin styles into classes in showthread
- [x] Move alternate forums cancer representations into a class [(test)](http://forums.somethingawful.com/showthread.php?threadid=3762325&pagenumber=1&perpage=40#post455641179)
- [ ] Move 'Who posted?' styles into classes
- [ ] Switch CSS class adding to `Element.classList.add()` [(MDN ref)](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
